language: ruby
sudo: false
script:
  - time bundle exec rake test_with_coveralls
rvm:
  - 1.9.3
  - 2.1.2
env:
  matrix:
    - RAILS=3.2.19
    - RAILS=4.1.4
notifications:
  irc:
    channels:
      - "irc.freenode.org#activeadmin"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "(%{branch}/%{commit} by %{author}): %{message} (%{build_url})"
